### ISSUE TITLE
onError is not defined

### ISSUE THREAD

**Issue by esseb** [ForbesLindesay/redux-wait#2]
If one of my promises fail, redux-wait fails because `onError` is not defined.

```
ReferenceError: onError is not defined
   at /users/esseb/test/node_modules/redux-wait/lib/index.js:48:19
   at tryCallOne (/users/esseb/test/node_modules/redux-wait/node_modules/promise/lib/core.js:37:12)
   at /users/esseb/test/node_modules/redux-wait/node_modules/promise/lib/core.js:103:15
   at flush (/users/esseb/test/node_modules/redux-wait/node_modules/promise/node_modules/asap/raw.js:50:29)
   at process._tickDomainCallback (node.js:459:13)
```

https://github.com/ForbesLindesay/redux-wait/blob/b0493999b586ead3410f2166188172dd7f6f0ea2/src/index.js#L24 does an if test for `onError` which does not exist.

**Comment by chemoish** [comment]
https://github.com/ForbesLindesay/redux-wait/blob/master/src/index.js#L46

`onFailure` vs `onError` :stuck_out_tongue:
